export enum EnvKeys {
  PORT = 'PORT',
  DATABASE_URL = 'DATABASE_URL',
  JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  FRONTEND_URL = 'FRONTEND_URL',
  NODE_ENV = 'NODE_ENV',
}
