export enum ErrorCode {
  BOOKING_SLOT_UNAVAILABLE = 'BOOKING_SLOT_UNAVAILABLE',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // HTTP_STATUS_CODES
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  BAD_REQUEST = 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // DEFAULT
  HTTP_ERROR = 'HTTP_ERROR',
}
